version: '3.7'

services:
    db:
        image: postgres:13-alpine
        restart: always
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: ex_mon
        container_name: ex-mon-postgres
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - '5432:5432'
volumes:
    pgdata: